### ISSUE TITLE
Error on default UsageAutomation filter when config products contains more that one product

### ISSUE THREAD

**Issue by sansalinas** [cloudblue/connect-python-sdk#115]
The problem when default 'product__id' filter is apply to query 

..
filters = super(UsageAutomation, self).filters(status, **kwargs)
if self.config.products:
	filters['product__id'] = ','.join(self.config.products)
return filters
...

If I have products XXX, YYY, in my config json, it generates next RQL
'/public/v1/listings?limit=1000&status=listed&product__id=xxx%2Cyyy'
And as result, Connect APi returns me the next error:
'Bad filter query.'

**Comment by marcserrat** [comment]
Fixed in automation and usage workflows in 20.3
