### ISSUE TITLE
class UsageFileAutomation has not complete doc comment for filters method

### ISSUE THREAD

**Issue by dkolvakh** [cloudblue/connect-python-sdk#125]
Actually, it is possible and sometimes required to pass list of statuses, but in this case IDE will report an issue, because of not complete doc comment in file https://github.com/cloudblue/connect-python-sdk/blob/master/connect/resources/usage_file_automation.py . Suggested fix:

Line 28:
```
-        :param str status: Status of the requests. Default: ``'ready'``.
+       :param Union[list[str],str] status: Status of the requests. Default: ``'ready'``.
```

**Comment by marcserrat** [comment]
Please use python openapi client instead.

is available at: github.com/cloudblue/connect-python-openapi-client
