### ISSUE TITLE
Separate the models in a separate repo.

### ISSUE THREAD

**Issue by othercodes** [cloudblue/connect-python-sdk#129]
Wondering if we can separate the models into a standalone repo so we can use it with DevOps EaaS technology. These models allow a good and programmatic way to handle the request objects.

**Comment by marcserrat** [comment]
Hi Othercodes.

Python SDK is deprecated and only maintained for issues. The official way to integrate with python is using the python open API client. Please take a look: https://github.com/cloudblue/connect-python-openapi-client

please note, EaaS ONLY provides support for open API client.
